import { useState } from "react";
import Header from "../components/Header";
import {
  labels,
  getReceiveTargets,
  getPaymentTargets,
} from "../utils/calculations";
import { money } from "../utils/money";

function AddTransactionPage({
  account,
  activeType,
  goBack,
  goHome,
  updateAccountRecords,
}) {
  const records = account.records || [];

  const [amount, setAmount] = useState("");
  const [title, setTitle] = useState("");
  const [receiveTarget, setReceiveTarget] = useState("");
  const [manualReceiveSource, setManualReceiveSource] = useState("");
  const [receiveMethod, setReceiveMethod] = useState("bank");
  const [paymentTarget, setPaymentTarget] = useState("");
  const [manualPaymentTarget, setManualPaymentTarget] = useState("");
  const [monthlyRepeat, setMonthlyRepeat] = useState(false);
  const [date, setDate] = useState(new Date().toISOString().slice(0, 10));

  const receiveTargets = getReceiveTargets(records);
  const paymentTargets = getPaymentTargets(records);

  const canRepeatMonthly =
    activeType === "fixedIncome" || activeType === "fixedExpense";

  function getMethodLabel(method) {
    if (method === "cash") return "Cash / Nakit";
    return "Bank / Banka";
  }

  function saveRecord() {
    if (!amount) return;

    const needsTitle =
      activeType === "fixedIncome" ||
      activeType === "extraIncome" ||
      activeType === "fixedExpense" ||
      activeType === "debt" ||
      activeType === "borrowed";

    if (needsTitle && !title.trim()) return;

    if (activeType === "received") {
      const sourceName = receiveTarget || manualReceiveSource;
      if (!sourceName.trim()) return;

      const methodLabel = getMethodLabel(receiveMethod);

      const newRecord = {
        id: Date.now(),
        type: activeType,
        title: `${sourceName} → ${methodLabel}`,
        amount: Number(amount),
        date,
        receiveTarget: sourceName,
        receiveMethod,
        currency: "USD",
      };

      updateAccountRecords(account.id, [newRecord, ...records]);
      goHome();
      return;
    }

    if (activeType === "payment") {
      const targetName = paymentTarget || manualPaymentTarget;
      if (!targetName.trim()) return;

      const newRecord = {
        id: Date.now(),
        type: activeType,
        title: targetName,
        amount: Number(amount),
        date,
        paymentTarget: targetName,
        currency: "USD",
      };

      updateAccountRecords(account.id, [newRecord, ...records]);
      goHome();
      return;
    }

    const newId = Date.now();

    const newRecord = {
      id: newId,
      type: activeType,
      title: title.trim(),
      amount: Number(amount),
      date,
      currency: "USD",
      monthlyRepeat: canRepeatMonthly ? monthlyRepeat : false,
      autoGenerated: false,
      repeatRootId: canRepeatMonthly && monthlyRepeat ? newId : undefined,
    };

    updateAccountRecords(account.id, [newRecord, ...records]);
    goHome();
  }

  return (
    <div className="app">
      <Header title={`${labels[activeType]} Ekle`} back={goBack} />

      <div className="helper-card">
        {activeType === "received" && (
          <p>Para aldığında kimden geldiğini ve sana nasıl verildiğini seç.</p>
        )}

        {activeType === "payment" && (
          <p>Ödeme yaparken sadece gerçek borçların ve sabit giderlerin görünür.</p>
        )}

        {activeType === "borrowed" && (
          <p>Emanet para borç değildir. Sadece ayrı bilgi olarak saklanır.</p>
        )}

        {canRepeatMonthly && (
          <p>Bu kaydı her ay otomatik oluşturmak istersen aylık tekrarı aç.</p>
        )}
      </div>

      <div className="form-card">
        {activeType !== "received" && activeType !== "payment" && (
          <input
            placeholder={
              activeType === "fixedIncome"
                ? "Gelir adı: Kurs, maaş..."
                : activeType === "extraIncome"
                ? "Ekstra gelir adı"
                : activeType === "fixedExpense"
                ? "Gider adı: Telefon, kira..."
                : activeType === "debt"
                ? "Borç adı: Visa, kredi kartı..."
                : activeType === "borrowed"
                ? "Emanet parayı kim verdi?"
                : "Başlık"
            }
            value={title}
            onChange={(e) => setTitle(e.target.value)}
          />
        )}

        {activeType === "received" && (
          <>
            {receiveTargets.length > 0 && (
              <select
                value={receiveTarget}
                onChange={(e) => {
                  setReceiveTarget(e.target.value);
                  setManualReceiveSource("");
                }}
              >
                <option value="">Kimden aldın? Seç</option>
                {receiveTargets.map((target) => (
                  <option key={target.name} value={target.name}>
                    {target.name} - kalan {money(target.remaining)}
                  </option>
                ))}
              </select>
            )}

            <input
              placeholder="Listede yoksa kimden geldi?"
              value={manualReceiveSource}
              onChange={(e) => {
                setManualReceiveSource(e.target.value);
                setReceiveTarget("");
              }}
            />

            <div className="method-box">
              <p>Para sana nasıl verildi?</p>

              <div className="method-buttons">
                <button
                  type="button"
                  className={receiveMethod === "cash" ? "method-active" : ""}
                  onClick={() => setReceiveMethod("cash")}
                >
                  Cash / Nakit
                </button>

                <button
                  type="button"
                  className={receiveMethod === "bank" ? "method-active" : ""}
                  onClick={() => setReceiveMethod("bank")}
                >
                  Bank / Banka
                </button>
              </div>
            </div>
          </>
        )}

        {activeType === "payment" && (
          <>
            {paymentTargets.length > 0 && (
              <select
                value={paymentTarget}
                onChange={(e) => {
                  setPaymentTarget(e.target.value);
                  setManualPaymentTarget("");
                }}
              >
                <option value="">Neyi ödedin? Seç</option>
                {paymentTargets.map((target) => (
                  <option key={target.name} value={target.name}>
                    {target.name} - kalan {money(target.remaining)}
                  </option>
                ))}
              </select>
            )}

            <input
              placeholder="Listede yoksa neyi ödedin?"
              value={manualPaymentTarget}
              onChange={(e) => {
                setManualPaymentTarget(e.target.value);
                setPaymentTarget("");
              }}
            />
          </>
        )}

        {canRepeatMonthly && (
          <div className="method-box">
            <p>Bu kayıt her ay otomatik eklensin mi?</p>

            <div className="method-buttons">
              <button
                type="button"
                className={monthlyRepeat ? "method-active" : ""}
                onClick={() => setMonthlyRepeat(true)}
              >
                Açık
              </button>

              <button
                type="button"
                className={!monthlyRepeat ? "method-active" : ""}
                onClick={() => setMonthlyRepeat(false)}
              >
                Kapalı
              </button>
            </div>
          </div>
        )}

        <input
          type="number"
          placeholder="Tutar yaz"
          value={amount}
          onChange={(e) => setAmount(e.target.value)}
        />

        <input
          type="date"
          value={date}
          onChange={(e) => setDate(e.target.value)}
        />

        <button onClick={saveRecord}>Kaydet</button>
      </div>
    </div>
  );
}

export default AddTransactionPage;