import { useEffect, useState } from "react";
import HomeScreen from "./pages/HomeScreen";
import DetailScreen from "./pages/DetailScreen";
import IntroScreen from "./components/IntroScreen";
import { starterAccounts } from "./data/starterData";

function addMonths(date, months) {
  const d = new Date(date);
  const day = d.getDate();
  const target = new Date(d.getFullYear(), d.getMonth() + months, 1);
  const lastDay = new Date(
    target.getFullYear(),
    target.getMonth() + 1,
    0
  ).getDate();

  target.setDate(Math.min(day, lastDay));

  return target;
}

function formatDate(date) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");

  return `${year}-${month}-${day}`;
}

function generateMonthlyRepeats(account) {
  const today = new Date();
  let records = account.records || [];

  records = records.map((record) => {
    if (record.monthlyRepeat && !record.repeatRootId && !record.autoGenerated) {
      return {
        ...record,
        repeatRootId: record.id,
      };
    }

    return record;
  });

  const templates = records.filter(
    (record) => record.monthlyRepeat && !record.autoGenerated
  );

  const generatedRecords = [...records];

  templates.forEach((template) => {
    const rootId = template.repeatRootId || template.id;
    const startDate = new Date(`${template.date}T00:00:00`);

    let cursor = addMonths(startDate, 1);

    while (
      cursor.getFullYear() < today.getFullYear() ||
      (cursor.getFullYear() === today.getFullYear() &&
        cursor.getMonth() <= today.getMonth())
    ) {
      const newDate = formatDate(cursor);
      const monthKey = newDate.slice(0, 7);

      const alreadyExists = generatedRecords.some(
        (record) =>
          record.repeatRootId === rootId &&
          record.date?.slice(0, 7) === monthKey &&
          record.id !== template.id
      );

      if (!alreadyExists) {
        generatedRecords.push({
          ...template,
          id: `${rootId}-${monthKey}`,
          date: newDate,
          monthlyRepeat: false,
          autoGenerated: true,
          repeatRootId: rootId,
        });
      }

      cursor = addMonths(cursor, 1);
    }
  });

  return {
    ...account,
    records: generatedRecords,
  };
}

function normalizeAccounts(list) {
  return list.map((account) => {
    const normalized = {
      ...account,
      password: account.password || "",
      recoveryQuestions: account.recoveryQuestions || [],
      recoveryLocked: account.recoveryLocked || false,
      persons: account.persons || [],
      goals: account.goals || [],
      records: (account.records || []).map((record) => {
        if (record.type === "cashIn") {
          return {
            ...record,
            type: "received",
            receiveTarget: record.source || record.title,
          };
        }

        return record;
      }),
    };

    return generateMonthlyRepeats(normalized);
  });
}

function App() {
  const [showIntro, setShowIntro] = useState(true);

  const [accounts, setAccounts] = useState(() => {
    const saved = localStorage.getItem("elTurcoFinanceAccounts");

    if (saved) {
      return normalizeAccounts(JSON.parse(saved));
    }

    return normalizeAccounts(starterAccounts);
  });

  const [selectedAccountId, setSelectedAccountId] = useState(null);

  useEffect(() => {
    localStorage.setItem("elTurcoFinanceAccounts", JSON.stringify(accounts));
  }, [accounts]);

  const selectedAccount = accounts.find(
    (account) => account.id === selectedAccountId
  );

  function updateAccountRecords(accountId, newRecords) {
    setAccounts(
      accounts.map((account) =>
        account.id === accountId
          ? generateMonthlyRepeats({ ...account, records: newRecords })
          : account
      )
    );
  }

  function updateAccountPersons(accountId, newPersons) {
    setAccounts(
      accounts.map((account) =>
        account.id === accountId
          ? { ...account, persons: newPersons }
          : account
      )
    );
  }

  function updateAccountGoals(accountId, newGoals) {
    setAccounts(
      accounts.map((account) =>
        account.id === accountId
          ? { ...account, goals: newGoals }
          : account
      )
    );
  }

  function updateAccountSecurity(accountId, updates) {
    setAccounts(
      accounts.map((account) =>
        account.id === accountId ? { ...account, ...updates } : account
      )
    );
  }

  function deleteAccount(accountId) {
    const account = accounts.find((item) => item.id === accountId);
    const accountName = account?.name || "bu hesap";

    const ok = window.confirm(
      `${accountName} hesabını tamamen kaldırmak istediğine emin misin? Bu işlem geri alınamaz.`
    );

    if (!ok) return;

    const updatedAccounts = accounts.filter((item) => item.id !== accountId);

    setAccounts(updatedAccounts);
    localStorage.setItem(
      "elTurcoFinanceAccounts",
      JSON.stringify(updatedAccounts)
    );

    setSelectedAccountId(null);
  }

  function importAllData(importedAccounts) {
    const cleanAccounts = normalizeAccounts(importedAccounts);

    setAccounts(cleanAccounts);
    localStorage.setItem(
      "elTurcoFinanceAccounts",
      JSON.stringify(cleanAccounts)
    );

    setSelectedAccountId(null);
  }

  function resetAllData() {
    const ok = window.confirm("Bütün kayıtları silmek istediğine emin misin?");
    if (!ok) return;

    localStorage.removeItem("elTurcoFinanceAccounts");
    setAccounts([]);
    setSelectedAccountId(null);
  }

  if (showIntro) {
    return <IntroScreen onFinish={() => setShowIntro(false)} />;
  }

  if (selectedAccount) {
    return (
      <DetailScreen
        account={selectedAccount}
        accounts={accounts}
        goBack={() => setSelectedAccountId(null)}
        updateAccountRecords={updateAccountRecords}
        updateAccountPersons={updateAccountPersons}
        updateAccountGoals={updateAccountGoals}
        updateAccountSecurity={updateAccountSecurity}
        deleteAccount={deleteAccount}
        importAllData={importAllData}
      />
    );
  }

  return (
    <HomeScreen
      accounts={accounts}
      setAccounts={setAccounts}
      openAccount={(account) => setSelectedAccountId(account.id)}
      resetAllData={resetAllData}
    />
  );
}

export default App;